export const PERMISSION_ACTIONS = {
    FETCH_START: 'FETCH_START',
    FETCH_SUCCESS: 'FETCH_SUCCESS',
    FETCH_ERROR: 'FETCH_ERROR',
    ADD_PERMISSION: 'ADD_PERMISSION',
    ADD_ERROR: 'ADD_ERROR',
    UPDATE_PERMISSION: 'UPDATE_PERMISSION',
    UPDATE_ERROR: 'UPDATE_ERROR',
  } as const;